version: '3'

services: 
    server:
        build:
            context: .
        command: [/root/phx.sh]
        volumes:
            - "./hoge:/root/hoge:rw"
        devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"
            #- "/dev/ttyACM0:/dev/ttyACM0"  
        ports:
            - "4000:4000"
